### ISSUE TITLE
BB2 Worksheets - Page 8 (Book 2 pp. 14-15)

### ISSUE THREAD

**Issue by rryman** [rryman/BB2-Worksheets#10]
Edits for Rhonda in original Word Doc.
- [ ] Remove extra space: first line, between "qualification" and "-":
"The basic contact sign (oblique line) – not the qualification * – shows the height of the foot. Draw"
- [x] Remove extra space: third line, between "making and sure" and "knee and line":
"height. Then add the line or open dot qualification, making - sure it does not touch the knee - line."
- [x] Remove random "s" from the end of the top of the bottom stave in original Word Doc.

Tick and close this issue.

**Comment by rsryman** [comment]
I checked and there is only 1 space between "qualification" and "-" (maybe looks longer after the italicized "n" ?)
