### ISSUE TITLE
BB2 Worksheets - Contact Signs

### ISSUE THREAD

**Issue by rryman** [rryman/BB2-Worksheets#12]
- [x] Rhonda to check contact signs - pp. 8, 11, 12. 13, 14, 15, 16, and 17

Please let me know if I have put the low contact signs low enough in all cases.
Is the difference between the contact sign for "shin/calf" and "just above ankle" height clear enough in all cases? Are there any places you think I should shrink the contact sign to show more of a difference?

**Comment by rsryman** [comment]
The contacts signs look fine. The only mid-space placement (after p. 8) is jeté ordinaire derrière (English) p. 16 and it is clearly distinct from the Italian and Russian placement.
