### ISSUE TITLE
Page 35 (Book 2 pp. 118 and 119)

### ISSUE THREAD

**Issue by rryman** [rryman/BB2-Worksheets#19]
In the notation, the first retire should be higher than the other two retires as it is English, Italian, then Russian. Robyn will fix it in the worksheets. Rhonda can choose whether to fix the original MacBenesh example or not.

**Comment by rryman** [comment]
Robyn also made the right arm higher in the Russian jete.

**Comment by rsryman** [comment]
Original notation fixed in MacBenesh.
