### ISSUE TITLE
Final Version to be sent to Canan

### ISSUE THREAD

**Issue by rryman** [rryman/BB2-Worksheets#22]
Here is the final version. 

As discussed you will check pages 5 and pages 32 - 35 to make sure the text and time signatures and tempos are okay. Once you have approved it, we will send a copy to Canan to look over before I post it on the server.

[B4B_Book2_Worksheets.pdf](https://github.com/rryman/BB2-Worksheets/files/2747184/B4B_Book2_Worksheets.pdf)

**Comment by rsryman** [comment]
All checked. Good to go. Is the following email ok?

Hello Canan,

We have attached what we hope is the final pdf for Benesh for Ballet Book 2 Worksheets.

We want to make sure that the text and notation display correctly on computers other than ours. 

Please let us know if you have time to give them a quick look before we put them up on the website for general distribution.

All the best in the new year.

Robyn and Rhonda

**Comment by rryman** [comment]
That email sounds fine. I'll copy it and send it off to Canan with the pdf.
