### ISSUE TITLE
LatestVersionBB2Worksheets

### ISSUE THREAD

**Issue by rsryman** [rryman/BB2-Worksheets#5]
[BB2WorksheetsNov14,2018.pdf](https://github.com/rryman/BB2-Worksheets/files/2581515/BB2WorksheetsNov14.2018.pdf)

**Comment by rsryman** [comment]
[BB2WorksheetsNov19,2018.pdf](https://github.com/rryman/BB2-Worksheets/files/2596967/BB2WorksheetsNov19.2018.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 1 - 7 (inclusive) - on November 20th 2018 at 11:00 am.

- [ ] Rhonda to download and proofread
 
[BB2Worksheets20NovP7.pdf](https://github.com/rryman/BB2-Worksheets/files/2600528/BB2Worksheets20NovP7.pdf)

**Comment by rsryman** [comment]
p. 4: 2 typos (error highlighted in bold) 
title: **Jumps** Lines (Book 2 p. 10) -> Jump Lines (Book 2 p. 10)
para 1 final sentence: Keep the jump line as shallow as possible, **maintain** the clear curve shape. -> Keep the jump line as shallow as possible, maintaining the clear curve shape.

**Comment by rryman** [comment]
I will make these changes in the pdf with Adobe Illustrator, but you should also change them in your original word doc.

**Comment by rsryman** [comment]
Will do.

**Comment by rryman** [comment]
Robyn has edited pages 8 - 12 (inclusive) - on November 21st 2018 at 11:15 am.
- [ ] Rhonda to download and proofread

[BB2Worksheets21NovP12.pdf](https://github.com/rryman/BB2-Worksheets/files/2604962/BB2Worksheets21NovP12.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 13 - 17 (inclusive) - on November 21st 2018 at 4:00 pm.

- [ ] Rhonda to download and proofread

[BB2Worksheets21NovP17.pdf](https://github.com/rryman/BB2-Worksheets/files/2605766/BB2Worksheets21NovP17.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 17 - 20 (inclusive) - on December 4th 2018 at 4:30 pm.

Rhonda to download and proofread. Separate proofreading entry made in GitHub for Rhonda to check off. (Proofreading - BB2Worksheets4Dec.P20.pdf #15)

[BB2Worksheets4Dec.P20.pdf](https://github.com/rryman/BB2-Worksheets/files/2646171/BB2Worksheets4Dec.P20.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 21 - 23 (inclusive) - on December 11st 2018 at 5:00 pm.

- [ ] Rhonda to proofread

[BB2Worksheets11Dec.P23.pdf](https://github.com/rryman/BB2-Worksheets/files/2669623/BB2Worksheets11Dec.P23.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 23 - 26 (inclusive) - on December 18th 2018 at 4:00 pm.
- [ ] Rhonda to proofread

[BB2Worksheets18Dec.P26.pdf](https://github.com/rryman/BB2-Worksheets/files/2692212/BB2Worksheets18Dec.P26.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 29 - 30 (inclusive) - on January 2nd 2019 at 5:30    

- [ ] Rhonda to proofread

[BB2Worksheets02JanP30.pdf](https://github.com/rryman/BB2-Worksheets/files/2722270/BB2Worksheets02JanP30.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 31 - 33 (inclusive) - on January 8th 2019 at 12:30

For Rhonda's information:

- As of page 32, Robyn changed the fifth position signs to match the previous pages (Rhonda had started using 5th position signs with a larger dot and a shorter horizontal line).
- Robyn started removing bar lines in the blank staves (as previously agreed by Rhonda and Robyn).
- Page 33 - Robyn added a period after "Without aerial positions" to be consistent.

- [ ] Rhonda to proofread

[BB2Worksheets08JanP33.pdf](https://github.com/rryman/BB2-Worksheets/files/2737838/BB2Worksheets08JanP33.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 38 - 40 (inclusive) - on January 9th 2019 at 3:45

- [ ] Rhonda to proofread

[BB2Worksheets09JanP40.pdf](https://github.com/rryman/BB2-Worksheets/files/2742549/BB2Worksheets09JanP40.pdf)
