### ISSUE TITLE
Instruction page 3

### ISSUE THREAD

**Issue by rryman** [rryman/BB2-Worksheets#6]
We also start doing sequences and not positions in these worksheets.
Update instructions accordingly, as you did for BB3 and BB4 worksheets?

In order to reinforce your ability to read BMN, you should stand up and perform each **sequence** before attempting to copy it.
Don't copy blindly, but rather make sure you understand each sequence notated and the relevant Benesh theory.

**Comment by rsryman** [comment]
I'm getting confused. You don't want global updates but you DO want me to
edit this instruction re BB3 & BB4 worksheets, yes?

I will not upload the few changes I have input re BB3 today until I here
from you.

**Comment by rryman** [comment]
This comment was in relation to BB2 Worksheets. The instructions right at the very beginning of the worksheets still say each **position** and not each **sequence**. You updated it already for BB3 and BB4 worksheets, but not for BB2 Worksheets.

**Comment by rsryman** [comment]
Done. I'll upload the new pdf when I have done all of todays edits.
