### ISSUE TITLE
Updating PDF

### ISSUE THREAD

**Issue by rryman** [rryman/BB2-Worksheets#7]
- [x] Rhonda to fix instructions on page 3.
- [x] Rhonda to change footer to December 2018.
- [x] Robyn to start updating PDF using Adobe Illustrator.
- [x] After each editing session, Robyn will upload the latest version of the PDF to GitHub.
- [x] Rhonda will download the latest version and will proofread the pages Robyn updates when she completes an editing session.

**Comment by rsryman** [comment]
First two items done and new pdf uploaded.
